apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: plfotos-com-tls
spec:
    SecretName: plfotos-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: plfotos.com
    dnsNames:
        - plfotos.com
        - www.plfotos.com
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - plfotos.com
                - www.plfotos.com
